// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240723090855_sdfghjkl")]
    partial class sdfghjkl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VRExperienceID")
                        .HasColumnType("int");

                    b.HasKey("AttendeeID");

                    b.HasIndex("VRExperienceID");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("dotnetapp.Models.VRExperience", b =>
                {
                    b.Property<int>("VRExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VRExperienceID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VRExperienceID");

                    b.ToTable("VRExperiences");

                    b.HasData(
                        new
                        {
                            VRExperienceID = 1,
                            Description = "Explore the wonders of space in a fully immersive virtual reality experience.",
                            EndTime = "2023-01-01T12:00:00",
                            ExperienceName = "Virtual Space Exploration",
                            Location = "Virtual",
                            MaxCapacity = 10,
                            StartTime = "2023-01-01T10:00:00"
                        },
                        new
                        {
                            VRExperienceID = 2,
                            Description = "Take a tour through history with this engaging VR experience.",
                            EndTime = "2023-01-11T13:00:00",
                            ExperienceName = "Historical VR Tour",
                            Location = "Virtual",
                            MaxCapacity = 10,
                            StartTime = "2023-01-11T10:00:00"
                        },
                        new
                        {
                            VRExperienceID = 3,
                            Description = "Dive into the depths of the ocean and explore underwater life like never before.",
                            EndTime = "2023-02-01T16:00:00",
                            ExperienceName = "Underwater Adventure",
                            Location = "Virtual",
                            MaxCapacity = 10,
                            StartTime = "2023-02-01T14:00:00"
                        },
                        new
                        {
                            VRExperienceID = 4,
                            Description = "Experience the thrill of mountain climbing from the safety of your home.",
                            EndTime = "2023-02-15T11:00:00",
                            ExperienceName = "Mountain Climbing Expedition",
                            Location = "Virtual",
                            MaxCapacity = 10,
                            StartTime = "2023-02-15T09:00:00"
                        },
                        new
                        {
                            VRExperienceID = 5,
                            Description = "Travel back in time to ancient Rome and witness its grandeur and history.",
                            EndTime = "2023-03-01T12:00:00",
                            ExperienceName = "Ancient Rome Tour",
                            Location = "Virtual",
                            MaxCapacity = 10,
                            StartTime = "2023-03-01T10:00:00"
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.Attendee", b =>
                {
                    b.HasOne("dotnetapp.Models.VRExperience", "VRExperience")
                        .WithMany("Attendees")
                        .HasForeignKey("VRExperienceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VRExperience");
                });

            modelBuilder.Entity("dotnetapp.Models.VRExperience", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
